#!/bin/bash

# Dotfiles installer.
#   Based on https://github.com/leonjza/dotfiles. Shouts to @leonjza
#   In truth its probably a copy, not based of anything 

# This script is structured in the following way:
#
#   Default variable values such as git path & commandline arguments
#   Helper functions such as color output
#   Function definitions with the *actual* logic
#   Small helper to ensure the commands needed for this installer is available
#   Commandline argument parser at the bottom to decide what gets called
#
#   For more, see the README file at $gitorigin

set -e  

# static variables
gitpath="$HOME/.dotfiles"
gitorigin="https://github.com/CryDeTaan/dotfiles.git"
gitoriginSSH="git@github.com:CryDeTaan/dotfiles.git"
debug=false

# configurations this script knows how to setup
declare -a configurations=("all" "none" "zsh" "vim")

# defaults for commandline options
install_target=false
uninstall_target=false
update=false
showusage=false

# defaults for file & config locations
oh_my_zsh="$HOME/.oh-my-zsh"
zsh_rc="$HOME/.zshrc"
vim_plugin_dir="$HOME/.vim"
vim_rc="$HOME/.vimrc"
rc_backup_dir="$HOME/.dotfiles.d/backups"

# helper functions
# colors!

function echo_func_start() { command echo -e "$(tput setaf 4; tput bold; tput smul)$* $(tput sgr0)";} # Function Start Heading.










function echo_blank() { command echo -e ""; } # Blank line
function echo() { command echo -e " [-] $*"; } # General Information is given - I like a lot of feedback
function echo_green() { command echo -e " [+] $(tput setaf 2; tput bold)$*$(tput sgr0)"; } # When a task finishes successfully
function echo_red() { command echo -e " [!] $(tput setaf 1)$*$(tput sgr0)"; } # When a task fails
function echo_yellow() { command echo -e " [*] $(tput setaf 3)$*$(tput sgr0)"; } # When a task is about to run.
function echo_debug() { if [ "$debug" = true ]; then command echo -e "$(tput setaf 3; tput bold)>>> $*$(tput sgr0)"; fi }
# directories!
function pushd() { command pushd "$@" > /dev/null; }
function popd() { command popd "$@" > /dev/null; }
# curl
function curl() { command curl -fsSL "$1" -o "$2"; }

# app logic
function usage() {

    cat <<EOF
    #################
    Simple Dotfiles installer
    #################
    Based on https://github.com/leonjza/dotfiles. Shouts to @leonjza
    
    Usage: install [option] [configs]

    Examples:
        install --install all
        install --install vim
        install --remove all
        install --remove vim
        install --update all
        install --check all

    Options:
        -i, --install [configs]     Install configurations (See Valid Configs)
        -r, --remove [configs]      Uninstall configurations (See Valid Configs)
        -u, --update all            Update the configuration repository

    Valid Configs:
        ${configurations[@]}
EOF

}



function install_components() {

    # check that the install target is something we know if
    validate_configuration $install_target

    # Ensure that we have the source repository ready in $gitpath
    prepare_git
    echo_debug "Installing: $install_target"

    case $install_target in
        none)
            echo_yellow "Installing nothing..."
            return
        ;;
        all)
            install_zsh
            install_vim
        ;;
        zsh)
            install_zsh
        ;;
        vim)
            install_vim
        ;;
    esac

}






function prepare_git() {

# Perparing git:
# 1. Check if a file with the name of gitpath exists - exit if this is the case.
# 2. Check if a directory with the name of gitpath exists - if so do the following check:
#       i.  Exit if the directory is not a git repository.
#       ii. If the direcotry is a git repository, check config to confirm
#           its has the same remote origin and perform update_repo.
# 3. Lastly if the path does not exist, perform a git clone of the repository to gitpath. 

    echo_yellow "Preparing git folder at: $gitpath"
    echo_blank

    # if there is already a file called .dotfiles, error out for manual inspection
    if [[ -f $gitpath ]]; then

        echo_red "$gitpath appears to be an existing file. Inspect/remove it first, then rerun the installer to continue"
        exit 1

    fi

    # Check if the the gitpath already exists, if so do some checks to make sure its 
    # in line with the repo
    if [[ -d $gitpath ]]; then
        # some more work is needed to to see if the repo is sane
        echo_yellow "$gitpath is a existing directory, inspecting it."
        echo_blank
        pushd $gitpath

        # check if we are inside a valid git repository
        valid_repo=$(set +e; git rev-parse --is-inside-work-tree 2>/dev/null; set -e)
        if [[ ! "$valid_repo" = true ]]; then

            echo_red "$gitpath is a directory, but not a valid git repository." 
            echo_red "Move/delete it first, then rerun the install to continue."
            exit 1

        fi

        echo_green "$gitpath is a existing git repository,"
        echo_blank
        echo_yellow "Inspecting it.."
        echo_blank

        # get the remote origin of the existing repository and check it
        localorigin=$(git config --get remote.origin.url)
        echo "Local git origin is: $localorigin"

        if [[ ! "$localorigin" = $gitorigin ]]; 

            then
                echo_red "It looks like the origin for the local dotfiles repo does not match."
                echo_red "The local origin is $localorigin and it should be $gitorigin"
                exit 2

            elif [ "$localorigin" = $gitorigin ]
            
                then
                echo_red "The local origin $localorigin matches the $gitorigin"
                echo_red "The script will now exit, run the updater to update the config"
                exit 2

        fi

        popd

        return
        
    fi


    # if the path does not exist, just clone it. there, easy.
    if [[ ! -d $gitpath ]]; then

        echo_yellow "Git repo in $gitpath does not exist. Cloning dotfiles repository: $gitorigin"
        git clone $gitorigin $gitpath
        echo_green "Done."

        echo_green "[+] Finished preparing git folder at: $gitpath"

        return

    fi


}

function validate_configuration() {

    # This check the user provided arguments

    local config=$1
    echo_debug "Looking for '$config' in the valid configurations.."
    for element in "${configurations[@]}"; do

        if [[ "$element" == "$config" ]]; then
            echo "Configuration '$config' looks OK"
            return
        fi

    done

    echo_red "[!] $config is not a valid configuration"
    exit 1

}

function backup_config() {

    local config=$1

    # add a date to the config file
    local filename=$(basename $config-$(date +"%s"))

    # make sure the backup dir exists
    mkdir -p $rc_backup_dir

    # copy the config file to the backup dir
    echo_green "[+] Backing up config file $config"
    echo_debug "[-] Config backup goes to $rc_backup_dir/$filename"
    cp -f $config $rc_backup_dir/$filename

}


function restore_config() {

    local config=$1
    local base=$(basename $config)

    # search for the latest backup in the backup directory
    filename=$(ls -a $rc_backup_dir | grep $base | sort -n -t _ -k 2 | tail -1)
    echo_debug "Backupfile lookup returned: $filename"

    if [[ ! "$filename" == "" ]]; then

        echo_green "Restoring last backup of $base to $config which is $filename"
        cp -f $rc_backup_dir/$filename $config

    else
        echo_yellow "No backup of $config could be found. nothing to restore."
    fi
}


function install_zsh() {

    echo_func_start "Installing zsh"

    local temp="$(mktemp)"
    echo_yellow "Installing ZSH configuration"

    # make sure zsh is available
    if ! hash zsh 2>/dev/null; then
        echo_red "zsh is not installed or in your PATH. Not installing this configuration."
        return
    fi

    # Ensure that *.d directory exists
    echo_yellow "Creating *.d directory in $HOME/.dotfiles.d/zshrc.d"
    mkdir -p $HOME/.dotfiles.d/zshrc.d
    echo_green "Done."


    echo_yellow "Downloading oh-my-zsh installer, and"
    echo_yellow "Saving installer to $temp"
    curl "https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh" $temp
    echo_green "Done."

    echo "Preventing the installer from starting ZSH when its done"
    sed -i -r "s/env zsh//" $temp

    echo "Running oh-my-zsh installer..."
    echo "Using sh to run $temp"
    sh $temp
    echo "Removing downloaded installer"
    rm -f $temp

    echo "Installing plugins"
    echo "Using oh-my-zsh directory: $oh_my_zsh/custom/plugins"

    # Syntax highlighting
    if [[ ! -d "$oh_my_zsh/custom/plugins/zsh-syntax-highlighting" ]]; then
        git clone git://github.com/zsh-users/zsh-syntax-highlighting.git $oh_my_zsh/custom/plugins/zsh-syntax-highlighting
    else
        echo_red "Syntax highligthing plugin already exists, moving on."
    fi

    # Auto suggestions
    if [[ ! -d "$oh_my_zsh/custom/plugins/zsh-autosuggestions" ]]; then
        git clone git://github.com/zsh-users/zsh-autosuggestions $oh_my_zsh/custom/plugins/zsh-autosuggestions
    else
        echo_yellow "[!] Autosuggestions plugin already exists."
    fi

    echo "[*] Installing Zsh configuration file"

    ## Backup the current one
    if [[ -f "$zsh_rc" ]]; then
        backup_config $zsh_rc
    fi

    echo_debug "[-] Symlinking $gitpath/rc/zshrc to $zsh_rc"
    ln -sf $gitpath/rc/zshrc $zsh_rc

    echo "[-] Symlinking *.zsh files to $HOME/.dotfiles.d/zshrc.d/"
    ln -sf $gitpath/dotfiles.d/zshrc.d/* $HOME/.dotfiles.d/zshrc.d

    echo "[*] Installing custom zsh theme"

    if [[ ! -d "$$oh_my_zsh/custom/themes/" ]]; then
        echo "[+] Creating Directories $oh_my_zsh/custom/themes"
        mkdir -p $oh_my_zsh/custom/themes/
    fi

    echo "Symlinking zsh-theme file to $oh_my_zsh/custom/themes"
    ln -sf $gitpath/config/oh-my-zsh/custom/themes/crydetaan.zsh-theme $oh_my_zsh/custom/themes/crydetaan.zsh-theme

    echo_green "ZSH config install complete!"

}

function install_vim() {

    echo_green "Installing Vim configuration"

    # make sure vim is available
    if ! hash vim 2>/dev/null; then
        echo_red "vim is not installed or in your PATH. Not installing this configuration."
        return
    fi

    # Ensure that *.d directory exists
    echo_debug "Creating *.d directory in $HOME/.dotfiles.d/vimrc.d"
    mkdir -p $HOME/.dotfiles.d/vimrc.d

    echo_debug "Preparing the vim plugin directory at $vim_plugin_dir"
    mkdir -p $vim_plugin_dir

    echo "Installing Vim Plugins"

    # Vundle
    if [[ ! -d "$vim_plugin_dir/bundle/Vundle.vim" ]]; then
        git clone https://github.com/gmarik/Vundle.vim $vim_plugin_dir/bundle/Vundle.vim
    else
        echo_yellow "Vundle already exists."
    fi

    # Molokai
    if [[ ! -d "$vim_plugin_dir/bundle/molokai" ]]; then
        git clone https://github.com/tomasr/molokai $vim_plugin_dir/bundle/molokai
    else
        echo_yellow "Molokai color scheme already exists."
    fi

    echo "Installing Vim configuration file"

    ## Backup the current one
    if [[ -f "$vim_rc" ]]; then
        backup_config $vim_rc
    fi

    echo_debug "Symlinking $gitpath/rc/vimrc to $vim_rc"
    ln -sf $gitpath/rc/vimrc $vim_rc

    echo "Symlinking *.vim files to $HOME/.dotfiles.d/vimrc.d/"
    ln -sf $gitpath/dotfiles.d/vimrc.d/* $HOME/.dotfiles.d/vimrc.d

    echo "Running vim plugin installer"
    vim +PluginInstall +qall

    echo_green "Vim config install complete!"

}


function config_vim() {

    echo_green "Configuring Vim."

    # make sure vim is available
    if ! hash vim 2>/dev/null; then
        echo_red "vim is not installed or in your PATH. Not installing this configuration."
        return
    fi

    # Ensure that *.d directory exists
    echo_debug "Creating *.d directory in $HOME/.dotfiles.d/vimrc.d"
    mkdir -p $HOME/.dotfiles.d/vimrc.d

    echo_debug "Preparing the vim plugin directory at $vim_plugin_dir"
    mkdir -p $vim_plugin_dir

    echo "Installing Vim Plugins"

    # Vundle
    if [[ ! -d "$vim_plugin_dir/bundle/Vundle.vim" ]]; then
        git clone https://github.com/gmarik/Vundle.vim $vim_plugin_dir/bundle/Vundle.vim
    else
        echo_yellow "Vundle already exists."
    fi

    echo "Installing Vim configuration file"

    echo_debug "Symlinking $gitpath/rc/vimrc to $vim_rc"
    ln -sf $gitpath/rc/vimrc $vim_rc

    echo "Symlinking *.vim files to $HOME/.dotfiles.d/vimrc.d/"
    ln -sf $gitpath/dotfiles.d/vimrc.d/* $HOME/.dotfiles.d/vimrc.d

    echo "Running vim plugin installer"
    vim +PluginInstall +qall

    echo_green "Vim config install complete!"

}

function update_repo() {

    prepare_git

    echo_debug "Running git pull on $gitpath"
    pushd $gitpath
    git pull
    popd

    echo "Updating symlinks"

    if [[ -d "$HOME/.dotfiles.d/zshrc.d/" ]]; then ln -sf $gitpath/dotfiles.d/zshrc.d/* $HOME/.dotfiles.d/zshrc.d; fi
    if [[ -d "$HOME/.dotfiles.d/vimrc.d/" ]]; then ln -sf $gitpath/dotfiles.d/vimrc.d/* $HOME/.dotfiles.d/vimrc.d; fi

    echo_green "Update complete. You may want to close/re-open your session for changes to take effect."
}



# start by checking the software needed by this installer
# if we cant find it, rather die
for cmd in "curl" "git"; do

    if ! hash $cmd 2>/dev/null; then
        echo_red "'$cmd' can not be found. Please install it before using this script."
        exit 2
    fi
    echo_debug "Using $cmd from $(which $cmd)"

done

# parse commandline arguments
if [[ $# -gt 1 ]]; then

    while [[ $# -gt 1 ]]; do
        case $1 in
        -i|--install)
        install_target="$2"
        shift # past argument
        ;;
        -r|--remove)
        uninstall_target="$2"
        shift # past argument
        ;;
        -u|--update)
        update=true
        shift # past argument
        ;;
        *)
        showusage=true
        ;;
    esac

    shift # past argument or value
    done
else
    echo_debug "Running usage(), no args -gt 1 found"
    usage
fi

# usage
if [ "$showusage" = true ]; then
    usage
    exit 2
fi

# install
if [[ ! "$install_target" = false ]]; then
    echo "Running install on: $install_target"
    install_components
fi

if [[ ! "$uninstall_target" = false ]]; then
    echo "Running uninstall on: $uninstall_target"
    uninstall_components
fi

if [[ "$update" = true ]]; then
    echo "Running repo update"
    update_repo
fi
